### ISSUE TITLE
Loading Crash at 99%

### ISSUE THREAD

**Issue by AnonymousLol69** [LEVIXDDLMAO/I-hate-my-life#2]
Yeah, so I know this issue has already been listed, but it says the repository hasn't been updated for 2 months, so I wanted to see if you were fixing this port atm or your other ports. I also wanted to know what asset determines the version of HaxeFlixel you use.

**Comment by LEVIXDDLMAO** [comment]
dude leave me the fuck alone. do you see this being updated?
